version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: recipeuser
      DB_PASSWORD: recipepass
      DB_NAME: recipedb
      DB_PORT: 5432
    volumes:
      - .:/app
      - ./templates:/app/templates
    networks:
      - app-network
    # コンテナ内でアプリケーションを自動的に再起動するためのコマンドを追加することもできます
    # command: sh -c "go build -o main . && ./main"
    # または、ライブリロードツールを使用する場合はそのコマンドを指定します

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: recipeuser
      POSTGRES_PASSWORD: recipepass
      POSTGRES_DB: recipedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge